spring.datasource.url=jdbc:postgresql://localhost:5432/yourdatabase
spring.datasource.username=yourusername
spring.datasource.password=yourpassword

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update